apiVersion: v1
kind: Pod
metadata:
  name: phoenix-pop-kube-shell
spec:
  containers:
  - name: phoenix-pop-kube-shell
    image: chgu82837/phoenix-pop-kube:0.1.1
    command: ["tail", "-f", "/dev/null"]
    env:
      - name: DATABASE_URL
        value: "postgres://app:apppass@mypostgres.default.svc.cluster.local/pop_kube_1"
      - name: SECRET_KEY_BASE
        value: "9m/uL4JbdJjVWqEioFQKv76OxnNJnUk1CnNedhI2MUlwhPR+3NecUcn91N64xTWm"

# kubectl apply -f app-shell.yml
# kubectl exec --stdin --tty phoenix-pop-kube-shell -- /bin/bash
#   ./bin/migrate # or anything inside phoenix-pop-kube app
