apiVersion: v1
kind: Secret
metadata:
  name: main-postgres-app-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: base64url # prevent slash breaking DATABASE_URL
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: main-app-key-base-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "64" # phoenix require SECRET_KEY_BASE to to be at least 64 bytes
data: {}
