apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: main-postgres
spec:
  replicas: 3
  image: postgres:14.1
  database:
    size: 1Gi # volume size is claimed by Gi in digital ocean 
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: main-postgres-super-secret
          key: password
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: main-postgres-replication-secret
          key: password
